# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

# Disable all linters
DISABLE_LINTERS:
  - all

# Enable only the Groovy linter
ENABLED_LINTERS:
  - GROOVY

# Groovy Linter settings
GROOVY_NPM_GROOVY_LINT_RULES_PATH: LINTER_DEFAULT

# Remove checking of the file names
SPELL_CSPELL_ANALYZE_FILE_NAMES: false

# Whether to apply fixes
APPLY_FIXES: none

# Show elapsed time in logs
SHOW_ELAPSED_TIME: true
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
